# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9.4.1
xcode_workspace: GithubAPI.xcworkspace
xcode_scheme: GithubAPI_Example
before_install:
  - gem install cocoapods
  - cd Example
  - pod install
